name: {{cookiecutter.conda_package_name}}
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - make
  - cmake
  # Host dependencies
  - xeus >= 2.0
  - nlohmann_json
  - cppzmq
  - xtl
  # Test dependencies
  - pytest
  - jupyter_kernel_test
  - nbval
  - pytest-rerunfailures