name: {{cookiecutter.conda_package_name}}-wasm-host
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - nlohmann_json
  - xeus-lite >=4.0,<5.0
  - xeus >=5.0,<6.0
  - xtl >=0.8,<0.9
